// <auto-generated />
namespace UniversityExaminationMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update91 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update91));
        
        string IMigrationMetadata.Id
        {
            get { return "202003280928410_Update91"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
